#!/usr/bin/env bash
set -eu -o pipefail

usage() {
    echo "Usage: $0 [options] repository..."
    cat <<'EOF'
Update the subtree bundles.

Options:
  -h, --help            display help and exit
  -a, --all             Apply to all repos
  -r PATTERN            Apply only to repos matching PATTERN
EOF
}

preset_repos=(
    https://github.com/yssl/QFEnter
    https://github.com/rking/ag.vim
    https://github.com/msanders/cocoa.vim
    https://github.com/ciaranm/securemodelines
    https://github.com/majutsushi/tagbar
    https://github.com/martinlroth/vim-acpi-asl
    https://github.com/kchmck/vim-coffee-script
    https://github.com/sfiera/vim-emacsmodeline
    https://github.com/hunner/vim-plist
    https://github.com/mhinz/vim-signify
    https://github.com/tpope/vim-surround
    https://github.com/tpope/vim-repeat
    https://github.com/hsitz/VimOrganizer
    https://github.com/vim-scripts/zim-syntax
)

script_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

all=
repo_pattern=
while getopts 'ahr:-:' opt ; do
    if [[ "$opt" = "-" ]]; then opt="--$OPTARG"; unset OPTARG; fi

    case "$opt" in
    h|--help)
        usage
        exit 0
        ;;
    a)
        all=1
        ;;
    r)
        repo_pattern=$OPTARG
        ;;
    '?')
        usage >&2
        exit 2
        ;;
    *)
        echo >&2 "$0: illegal option -- $opt"
        exit 2
        ;;
    esac
done
shift $(( $OPTIND - 1 ))

repos=()
push_repos() { repos=( "${repos[@]:+${repos[@]}}" "$@" ) ; }

if [ -n "$repo_pattern" ] ; then
    for repo in "${preset_repos[@]}" ; do
        if [ -n "$repo_pattern" ] ; then
            if ! echo "$repo" | grep -q -e "$repo_pattern" ; then
                continue
            fi
        fi
        push_repos "$repo"
    done
elif [ -n "$all" ] ; then
    push_repos "${preset_repos[@]:+${preset_repos[@]}}"
fi
push_repos "$@"

for repo in "${repos[@]}" ; do
    ref=master
    basename=`basename "$repo" .git`
    prefix="bundle/`basename "$repo"`"
    if [ -d "$prefix" ] ; then
        git subtree pull -P "$prefix" --squash --message "$prefix: Pulled new '$ref' from '$repo'" "$repo" "$ref"
    else
        git subtree add  -P "$prefix" --squash --message "$prefix: Pulled new '$ref' from '$repo'" "$repo" "$ref"
    fi
done

